source:
  - name: HumanEval
    type: huggingface
    kwargs:
      path: openai/openai_humaneval
      sort_key: task_id
      split: test

dataset:
  - name: target
    type: dict
    kwargs:
      primary_key: id
      fields:
        - name: id
          source: HumanEval
          key: task_id
        - name: entry_point
          source: HumanEval
          key: entry_point
        - name: prompt
          source: HumanEval
          key: prompt
        - name: gold_tc
          source: HumanEval
          key: test

graph:
  entry_point: code

  edges:
    - pair: [code, parsed_code]
      type: always
    - pair: [parsed_code, __end__]
      type: always

  nodes:
    - name: code
      type: llm
      input_keys: [prompt]
      kwargs:
        n: 1
        output_key: llm_jun_out
        llm: !inc configs/llm/llama3_8b-greedy.yaml
        prompt:
          type: chat
          kwargs:
            body_template_paths: ["templates/prompt/DP"]
    - name: parsed_code
      type: parser
      input_keys: [llm_jun_out]
      kwargs:
        output_key: parser_jun_out
        type: code_block
      
